<?php

use Illuminate\Database\Seeder;

class DataTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_types')->delete();
        
        \DB::table('data_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'users',
                'slug' => 'users',
                'display_name_singular' => 'User',
                'display_name_plural' => 'Users',
                'icon' => 'voyager-person',
                'model_name' => 'TCG\\Voyager\\Models\\User',
                'policy_name' => 'TCG\\Voyager\\Policies\\UserPolicy',
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2019-01-10 07:25:28',
                'updated_at' => '2019-01-10 07:25:28',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'menus',
                'slug' => 'menus',
                'display_name_singular' => 'Menu',
                'display_name_plural' => 'Menus',
                'icon' => 'voyager-list',
                'model_name' => 'TCG\\Voyager\\Models\\Menu',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2019-01-10 07:25:28',
                'updated_at' => '2019-01-10 07:25:28',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'roles',
                'slug' => 'roles',
                'display_name_singular' => 'Role',
                'display_name_plural' => 'Roles',
                'icon' => 'voyager-lock',
                'model_name' => 'TCG\\Voyager\\Models\\Role',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2019-01-10 07:25:28',
                'updated_at' => '2019-01-10 07:25:28',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'ingredients',
                'slug' => 'ingredients',
                'display_name_singular' => 'Ingredient',
                'display_name_plural' => 'Ingredients',
                'icon' => NULL,
                'model_name' => 'App\\Ingredient',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-01-09 12:14:49',
                'updated_at' => '2019-02-13 06:43:21',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'kitchens',
                'slug' => 'kitchens',
                'display_name_singular' => 'Kitchen',
                'display_name_plural' => 'Kitchens',
                'icon' => NULL,
                'model_name' => 'App\\Kitchen',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-01-09 12:16:46',
                'updated_at' => '2019-01-14 09:54:01',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'meals',
                'slug' => 'meals',
                'display_name_singular' => 'Meal',
                'display_name_plural' => 'Meals',
                'icon' => NULL,
                'model_name' => 'App\\Meal',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-01-09 12:17:08',
                'updated_at' => '2019-03-14 08:37:02',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'weeks',
                'slug' => 'weeks',
                'display_name_singular' => 'Week',
                'display_name_plural' => 'Weeks',
                'icon' => NULL,
                'model_name' => 'App\\Week',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-01-09 12:19:29',
                'updated_at' => '2019-01-16 09:25:50',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'plans',
                'slug' => 'plans',
                'display_name_singular' => 'Plan',
                'display_name_plural' => 'Plans',
                'icon' => NULL,
                'model_name' => 'App\\Plan',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-01-09 12:19:41',
                'updated_at' => '2019-01-14 09:54:11',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'meal_category',
                'slug' => 'meal-category',
                'display_name_singular' => 'Meal Category',
                'display_name_plural' => 'Meal Categories',
                'icon' => NULL,
                'model_name' => 'App\\MealCategory',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-01-09 12:19:57',
                'updated_at' => '2019-01-09 12:19:57',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'customers',
                'slug' => 'customers',
                'display_name_singular' => 'Customer',
                'display_name_plural' => 'Customers',
                'icon' => NULL,
                'model_name' => 'App\\Customer',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-01-09 12:34:55',
                'updated_at' => '2019-02-24 11:10:11',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'meal_categories',
                'slug' => 'meal-categories',
                'display_name_singular' => 'Meal Category',
                'display_name_plural' => 'Meal Categories',
                'icon' => NULL,
                'model_name' => 'App\\MealCategory',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-01-09 13:11:33',
                'updated_at' => '2019-01-09 13:11:33',
            ),
            11 => 
            array (
                'id' => 13,
                'name' => 'meal_types',
                'slug' => 'meal-types',
                'display_name_singular' => 'Meal Type',
                'display_name_plural' => 'Meal Types',
                'icon' => 'voyager-backpack',
                'model_name' => 'App\\MealType',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-01-15 12:19:42',
                'updated_at' => '2019-01-15 12:19:42',
            ),
            12 => 
            array (
                'id' => 14,
                'name' => 'customer_meals',
                'slug' => 'customer-meals',
                'display_name_singular' => 'Customer Meal',
                'display_name_plural' => 'Customer Meals',
                'icon' => NULL,
                'model_name' => 'App\\CustomerMeal',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => 'Customers Meals List',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-01-22 05:42:21',
                'updated_at' => '2019-03-14 07:08:29',
            ),
            13 => 
            array (
                'id' => 15,
                'name' => 'ingredient_types',
                'slug' => 'ingredient-types',
                'display_name_singular' => 'Ingredient Type',
                'display_name_plural' => 'Ingredient Types',
                'icon' => NULL,
                'model_name' => 'App\\IngredientType',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2019-02-13 06:39:58',
                'updated_at' => '2019-03-04 08:15:10',
            ),
        ));
        
        
    }
}