<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-dashboard',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2019-01-10 07:25:28',
                'updated_at' => '2019-02-12 08:43:47',
                'route' => 'voyager.dashboard',
                'parameters' => 'null',
            ),
            1 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2019-01-10 07:25:28',
                'updated_at' => '2019-01-10 07:25:28',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2019-01-10 07:25:28',
                'updated_at' => '2019-01-10 07:25:28',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 14,
                'created_at' => '2019-01-10 07:25:28',
                'updated_at' => '2019-02-13 06:41:26',
                'route' => NULL,
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2019-01-10 07:25:28',
                'updated_at' => '2019-01-15 12:21:54',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2019-01-10 07:25:28',
                'updated_at' => '2019-01-15 12:21:54',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 15,
                'created_at' => '2019-01-10 07:25:28',
                'updated_at' => '2019-02-13 06:41:26',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Ingredients',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-params',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2019-01-09 12:14:50',
                'updated_at' => '2019-02-13 06:41:26',
                'route' => 'voyager.ingredients.index',
                'parameters' => 'null',
            ),
            8 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Kitchens',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lab',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2019-01-09 12:16:46',
                'updated_at' => '2019-02-13 06:41:26',
                'route' => 'voyager.kitchens.index',
                'parameters' => 'null',
            ),
            9 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Meals',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-pizza',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2019-01-09 12:17:08',
                'updated_at' => '2019-02-13 06:41:26',
                'route' => 'voyager.meals.index',
                'parameters' => 'null',
            ),
            10 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Weeks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-calendar',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2019-01-09 12:19:29',
                'updated_at' => '2019-02-13 06:41:26',
                'route' => 'voyager.weeks.index',
                'parameters' => 'null',
            ),
            11 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Plans',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-file-text',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2019-01-09 12:19:41',
                'updated_at' => '2019-02-13 06:41:26',
                'route' => 'voyager.plans.index',
                'parameters' => 'null',
            ),
            12 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Customers',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-group',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2019-01-09 12:34:55',
                'updated_at' => '2019-02-13 06:41:26',
                'route' => 'voyager.customers.index',
                'parameters' => 'null',
            ),
            13 => 
            array (
                'id' => 19,
                'menu_id' => 1,
                'title' => 'Meal Types',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-backpack',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2019-01-15 12:19:42',
                'updated_at' => '2019-02-13 06:41:26',
                'route' => 'voyager.meal-types.index',
                'parameters' => NULL,
            ),
            14 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => 'Customer Meals',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hotdog',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 12,
                'created_at' => '2019-01-22 05:42:21',
                'updated_at' => '2019-02-13 06:41:26',
                'route' => 'voyager.customer-meals.index',
                'parameters' => 'null',
            ),
            15 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Kitchens Calendar',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-calendar',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 13,
                'created_at' => '2019-02-10 08:41:06',
                'updated_at' => '2019-02-13 06:41:26',
                'route' => NULL,
                'parameters' => '',
            ),
            16 => 
            array (
                'id' => 32,
                'menu_id' => 1,
                'title' => 'Juices',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-dot',
                'color' => NULL,
                'parent_id' => 21,
                'order' => 1,
                'created_at' => '2019-02-11 09:07:53',
                'updated_at' => '2019-02-12 08:42:24',
                'route' => 'meals_calendar',
                'parameters' => '{"kitchen_id":1}',
            ),
            17 => 
            array (
                'id' => 33,
                'menu_id' => 1,
                'title' => 'Vegetables',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-dot',
                'color' => NULL,
                'parent_id' => 21,
                'order' => 2,
                'created_at' => '2019-02-11 09:07:53',
                'updated_at' => '2019-02-12 08:42:24',
                'route' => 'meals_calendar',
                'parameters' => '{"kitchen_id":2}',
            ),
            18 => 
            array (
                'id' => 34,
                'menu_id' => 1,
                'title' => 'Meat',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-dot',
                'color' => NULL,
                'parent_id' => 21,
                'order' => 3,
                'created_at' => '2019-02-11 09:07:53',
                'updated_at' => '2019-02-12 08:42:24',
                'route' => 'meals_calendar',
                'parameters' => '{"kitchen_id":3}',
            ),
            19 => 
            array (
                'id' => 35,
                'menu_id' => 1,
                'title' => 'Ingredient Types',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-dot-2',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2019-02-13 06:39:58',
                'updated_at' => '2019-02-13 06:41:26',
                'route' => 'voyager.ingredient-types.index',
                'parameters' => 'null',
            ),
        ));
        
        
    }
}